# Basic site configuration
# ------------------------
site_name: CS3 Chemoinformatics Summer School 2024 # Name of the site
site_url: https://fulopjoz.github.io/cs3-chemoinformatics-summer-school # Replace with your actual site URL
site_dir: ../public # Directory where the built site files will be placed
docs_dir: ../docs # Directory containing your documentation source files

# Repository configuration
# ------------------------
repo_url: https://gitlab.com/fulopjoz/chemoinformatics-summer-school # URL to your source code repository
repo_name: CS3 Chemoinformatics Summer School Notes # Name of the source code repository
edit_uri: -/blob/main/docs # URI to the source file in the repository, used for the "Edit this page" links

# Theme configuration
# -------------------
theme:
  name: material # Name of the theme
  features:
    - content.action.view # Enables the 'view' action button
    - content.code.copy # Adds copy button besides code blocks
  font:
    code: JetBrains Mono # Change code block font to JetBrains mono
  icon:
    repo: fontawesome/brands/gitlab # Icon for the repository link
    view: material/eye # Icon for the 'view' action button
  palette:
    # Palette for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-5
        name: Switch to light mode

# Markdown extensions
# -------------------
markdown_extensions:
  - footnotes # Enables support for footnotes
  - attr_list # Allows adding attributes to HTML tags
  - pymdownx.highlight # Syntax highlighting for code blocks
  - pymdownx.superfences # Extra fences for code blocks
  - pymdownx.details # Support for details/summary tags
  - pymdownx.magiclink # Automatic linking for URLs and email addresses
  - pymdownx.tasklist # Support for task lists
  - pymdownx.emoji # Emoji support
  - pymdownx.arithmatex # Support for LaTeX math
  - pymdownx.tabbed: # Support for block tabs in html page
        alternate_style: true
  - admonition # Support for admonitions (notes, warnings, etc.)
  - mdx_math # Math extension
  - plantuml_markdown # Support for PlantUML diagrams
  - toc: # Table of contents extension
        permalink: true # Enables permalinks for headings

# Extra resources
# ---------------
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML # MathJax for rendering math
  
extra_css:
  - extra.css # Additional CSS styles

# Plugins
# -------
plugins:
  - search # Adds a search bar to the site
  - roamlinks # Support for wikilinks similar to Roam Research and Obsidian
  - markdown-exec # Support for execution of code blocks
